server:
  port: 8081
spring:
  cloud:
    config:
      enabled: true
      server:
        git:
          label: master
          uri: E:\workspace\SPRING-CLOUD-SERVER
          search-paths: config-data
  application:
    name: cloud-server
