server:
  port: 8081
spring:
  cloud:
    config:
      server:
        native:
          searchLocations:
            file: E:/workspace/SPRING-CLOUD-SERVER
            search-paths: config-data
  application:
    name: config-service