server:
  port: 8081
spring:
  cloud:
    config:
      enabled: true
      server:
        git:
          basedir: E:\workspace\SPRING-CLOUD-SERVER\config-data
  application:
    name: cloud-server

