server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Neil2V/SPRING-EUREKA-CLOUD-CONFIG-GATEWAY
          search-paths: config-data
  application:
    name: cloud-server