server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Neil2V/SPRING-CLOUD-SERVER
          search-paths: config-data
  application:
    name: cloud-server
