server:
  port: 8081
spring:
  cloud:
    config:
      enabled: true
      server:
        native:
          searchLocations: file:/E:/workspace/SPRING-CLOUD-SERVER

  application:
    name: cloud-server
