server:
  port: 8082
spring:
  cloud:
    config:
      enabled: true
      server:
        git:
          default-label: master
          uri: https://github.com/Neil2V/SPRING-CLOUD-SERVER
          search-paths: config-data
  application:
    name: cloud-server

